project:
  type: website

website:
  title: "GIS Capacity Building"
  favicon: assets/logo.png
  search: false
  open-graph: true
  google-analytics: G-58N6NN1C47
  navbar:
    right:
      - text: Resources
        href: resources/
      - text: MapLogs
        href: map_logs/
      - text: Tools
        href: tools/
      - text: Data
        href: data_catalog/
      - text: About
        href: about/
  page-footer:
    left: "[Copyright &copy; 2026 Children's Environmental Health Initiative](/LICENCE)"
    center:
      - href: https://github.com/CEHI-code-repos/GISDataCatalog
        icon: github
        aria-label: GitHub
      - href: https://www.linkedin.com/company/children-s-environmental-health-initiative
        icon: linkedin
        aria-label: LinkedIn

format:
  html:
    theme:
      - cosmo
      - styles.scss
    page-layout: full
    toc: false

